# Generated by Django 2.0 on 2020-03-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name_name',
        ),
    ]
